### ISSUE TITLE
Error: Serial Port closed!... Error: End of file after updating docker image

### ISSUE THREAD

**Issue by kipusoep** [domoticz/domoticz#5261]
I'm running Domoticz using docker-compose on a RPi 4b 8GB using a USB SSD (powered).
Also connect via USB are a P1 smart meter, a RFXtrx433E USB 433.92MHz Transceiver and Slaesh's CC2652RB stick (Zigbee).
Since I've multiple USB devices connected and I noticed the ttyUSB-X changes after reboots, I've [created a symlink for them](https://www.domoticz.com/wiki/PersistentUSBDevices), which is working fine.
I also have a [Watchtower](https://github.com/containrrr/watchtower) container running to keep all the container up-to-date once a week.
When Domoticz gets updated and booted again, the connection with the P1 Smart Meter seems to be gone.
In the logs I noticed this message twice: `Error: Serial Port closed!... Error: End of file`
I used `cu` to see if the data of the device is flowing into the system and it seems alright.

Any clue what the issue migth be?
Might running a home assistant container with `privileged: true` cause this?

docker-compose:
```
domoticz:
    container_name: domoticz
    image: domoticz/domoticz
    devices:
      - '/dev/ttyUSB-RFX433:/dev/ttyUSB-RFX433'
      - '/dev/ttyUSB-P1:/dev/ttyUSB-P1'
    volumes:
      - ./domoticz:/opt/domoticz/userdata
      - ./domoticz/www/styles/machinon:/opt/domoticz/www/styles/machinon
    environment:
      - TZ=Europe/Amsterdam
      #- LOG_PATH=/opt/domoticz/userdata/domoticz.log
    networks:
      pub_net:
        ipv4_address: 10.0.0.20
    restart: unless-stopped
```
