### ISSUE TITLE
MQTT Auto discovery openBK(home assistant compatible)  RGBWW light discovered as RGBWZ light

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#5394]
i recently upgraded to 14599 in the hope that this light would be discovered correctly

According to home asistant this should be the correct config file for broadcasting
This is an RGBWW light which has RGB OR Warmwhite(color temperature can be changed using a slider)

The light however turns up in domoticz as RGBWZ
dim funtion works(but slider jumps back at 1%)
ON does not work
OFF WORKS
color changing does not work(i see 3 color circles instead of 1 color circle and 1 warm white circle)
i have absolutely no good working reference
maybe this config is wrong but it seems to work for the home assistant people

```
mqtt:
  light:
  - unique_id: "OpenBK7231T_17A1C483_light"
    name: "test 64"
    rgb_command_template: "{{ '#%02x%02x%02x0000' | format(red, green, blue)}}"
    rgb_value_template: "{{ value[0:2]|int(base=16) }},{{ value[2:4]|int(base=16) }},{{ value[4:6]|int(base=16) }}"
    rgb_state_topic: "lsclamp/led_basecolor_rgb/get"
    rgb_command_topic: "cmnd/lsclamp/led_basecolor_rgb"
    command_topic: "cmnd/lsclamp/led_enableAll"
    state_topic: "lsclamp/led_enableAll/get"
    availability_topic: "lsclamp/connected"
    payload_on: 1
    payload_off: 0
    brightness_command_topic: "cmnd/lsclamp/led_dimmer"
    brightness_scale: 100
    #brightness_value_template: "{{ value }}"
    color_temp_command_topic: "cmnd/lsclamp/led_temperature"
    color_temp_state_topic: "lsclamp/led_temperature/get"
    #color_temp_value_template: "{{ value }}"
```
