### ISSUE TITLE
login screen has returned

### ISSUE THREAD

**Issue by vespino** [domoticz/domoticz#5463]
After updating to the latest version (docker: 14853) I'm faced with the login screen again, although I whitelisted my network when login became mandatory a while back.

**Comment by kiddigital** [comment]
Can you run with some debugging enabled (`-loglevel all -debuglevel auth,webserver,received`) and share the output?

**Comment by vespino** [comment]
I'm not a Docker crack. I have created a custom container with docker-compose with a few settings and that works, but I have no idea how to add the debugging you requested. I'd be glad to, if you could tell me how.

**Comment by rezzalex** [comment]
Hello @vespino,
please have a look here : 
https://github.com/domoticz/domoticz/issues/5457#issuecomment-1353078834

**Comment by vespino** [comment]
Thank you, the container however won't start with that argument.

**Comment by kiddigital** [comment]
You need to _add_ these arguments (and not replace the original once)

**Comment by vespino** [comment]
I did.

This is my docker-compose.yml:

```
services:
  domoticz-php:
    build: .
    image: domoticz-php
    container_name: domoticz-php
    privileged: true
    restart: always
    network_mode: host
    environment:
      - WWW_PORT=0
      - SSL_PORT=8444
      - EXTRA_CMD_ARG="-loglevel all -debuglevel auth,webserver,received"
    volumes:
      - /volume4/docker/domoticz:/opt/domoticz/userdata
      - /volume1/homes/admain:/volume1/homes/admain
```

And my Dockerfile:

```
FROM domoticz/domoticz:latest
RUN apt-get update && apt-get upgrade -y && apt-get install etherwake php-cli php-xml php-soap -y && pip3 install tuyaha requests
```
