### ISSUE TITLE
autodiscovery hardware not correctly handlings brightness slider in colorpicker

### ISSUE THREAD

**Issue by akamming** [domoticz/domoticz#5575]
Referring to [this thread on the forum](https://www.domoticz.com/forum/viewtopic.php?p=298475#p298475)

The brightness slider in the colorpicker of a RGB switch does not work correctly
![image](https://user-images.githubusercontent.com/30364409/215309854-d961e539-9357-418b-8b1a-e98418a96134.png)

it should send an update of the brighntess value to mqtt, however it resends the current r,g and b values to mqtt

to reproduce:

1. Create an ESP Home sensor with the following YAML file
```
esphome:
  name: rgb_test
  platform: esp8266
  board: d1_mini

wifi:
  ssid: <SSID>
  password: <Secret>

# HASS API
api:

# Allow API
ota:

# Print Updates
logger:

# Example configuration entry
# Example configuration entry
light:
  - platform: rgb
    name: "Living Room Lights"
    red: output_component1
    green: output_component2
    blue: output_component3

# Example output entry
output:
  - platform: esp8266_pwm
    id: output_component1
    pin: D1
  - platform: esp8266_pwm
    id: output_component2
    pin: D2
  - platform: esp8266_pwm
    id: output_component3
    pin: D3

      # WebServer component, displays some information
web_server:
    port: 80

# Example configuration entry
mqtt:
  broker: <IP Adress of broker>
  username: <user>
  password: <pw>
```
2. Log MQTT output
`mosquitto_sub -h <MQTT host> -p <MQTT port> -u <MQTT User> -P <MQTT Password> -t "rgb_test/light/living_room_lights/command"`

3. enable autodiscovery in domoticz
4. click on "Living room lights" in domoticz (so the colorpicker appears)
5. click on the brightness slider bar.

EXPECTED Result: a message like {"brightness":128} (and the brightness of the LED changing)
ACTUAL Result: a message like {"color":{"b":100,"g":200,"r":50},"state":"ON"} (which have the same values as before, so lightness of LED not changing)

NOTE: 
You can shortcut the reproduction of the issue by  publishing 
`{"schema":"json","clrm":true,"supported_color_modes":["rgb"],"brightness":true,"name":"Living Room Lights","stat_t":"rgb_test/light/living_room_lights/state","cmd_t":"rgb_test/light/living_room_lights/command","avty_t":"rgb_test/status","uniq_id":"ESPlightliving_room_lights","dev":{"ids":"3c6105e37e8d","name":"rgb_test","sw":"esphome v2022.12.8 Jan 28 2023, 21:21:52","mdl":"d1_mini","mf":"espressif"}}` to topic `homeassistant/light/rgb_test/living_room_lights/config`
and so simulating the actual ESP Home sensor
